package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

public class CaselloController {
	@FXML
	private TextField txtCodiceCasello;
	@FXML
	private TextField txtCodAutostrada;
	@FXML
	private TextField txtAltezza;
	@FXML
	private TextField txtNomeCasello;

	public AppModel aggiungiCaselloModel = new AppModel();
	
	// Event Listener on Button.onAction
	@FXML
	public void aggiungiCasello(ActionEvent event) throws SQLException {
		// TODO Autogenerated
		boolean esiste=aggiungiCaselloModel.caselloPresente(txtNomeCasello.getText());
		
		if  (esiste) {
			
			 JOptionPane.showMessageDialog(null, "Impossibile aggiungere casello! Casello già presente");			
		}else{
			boolean aggiungi=aggiungiCaselloModel.aggiungiCas(txtCodiceCasello.getText(), txtNomeCasello.getText(),  txtAltezza.getText(), txtCodAutostrada.getText());
			if (aggiungi)
				
			    JOptionPane.showMessageDialog(null, "Casello aggiunto!");
		}
		try {
			((Node)event.getSource()).getScene().getWindow().hide(); 
			Stage primaryStage = new Stage();
			FXMLLoader loader = new FXMLLoader();
			Pane root=loader.load(getClass().getResource("/application/Amministratore.fxml").openStream());
			Scene scene = new Scene(root);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.show();		
		}catch(Exception e){
			
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void annulla(ActionEvent event) {
		// TODO Autogenerated
		try {
			((Node)event.getSource()).getScene().getWindow().hide(); 
			Stage primaryStage = new Stage();
			FXMLLoader loader = new FXMLLoader();
			Pane root=loader.load(getClass().getResource("/application/Amministratore.fxml").openStream());
			Scene scene = new Scene(root);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.show();		
		}catch(Exception e){
			
		}
	}
}
