package application.front.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import application.controller.AutostradaManager;
import application.controller.CaselloManager;
import application.model.Autostrada;
import application.model.Casello;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

public class CaselloController implements Initializable{
	
	@FXML private TextField txtAltezza;
	@FXML private TextField txtNomeCasello;
	@FXML private ComboBox<Autostrada> comboAutostrada;
	
	public CaselloManager cslmgr = new CaselloManager();
	// Event Listener on Button.onAction
	
	private ObservableList<Autostrada> elencoAutostrade = FXCollections.observableArrayList();
	private Casello casello = new Casello();
	private Autostrada autostradascelta = new Autostrada();
	
	//costruttore
	public CaselloController() {
		elencoAutostrade.setAll(AutostradaManager.getInstance().getAllAut());
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		comboAutostrada.setItems(this.elencoAutostrade);
		
	}
	
	public void getComboAutostrada(ActionEvent evt) {
		autostradascelta=comboAutostrada.getValue();
	}
	
	public void aggiungiCasello(ActionEvent event) throws SQLException {
		
			casello.setNomecasello(txtNomeCasello.getText());
			casello.setAltezza(Integer.parseInt(txtAltezza.getText()));
			casello.setAutostrada(autostradascelta);;
			
			boolean aggiungi=cslmgr.aggiungi(casello);
			
			if (aggiungi) {				
			    JOptionPane.showMessageDialog(null, "Casello aggiunto!");
				try {
					((Node)event.getSource()).getScene().getWindow().hide(); 
					Stage primaryStage = new Stage();
					FXMLLoader loader = new FXMLLoader();
					Pane root=loader.load(getClass().getResource("/application/front/fxml/Amministratore.fxml").openStream());
					Scene scene = new Scene(root);
					primaryStage.setScene(scene);
					primaryStage.show();		
				}catch(Exception e){
					e.printStackTrace();
				} 
			} else {System.out.println("ERRORE");}
	}
			

	// Event Listener on Button.onAction
	
	public void annulla(ActionEvent event) {
		// TODO Autogenerated
		try {
			((Node)event.getSource()).getScene().getWindow().hide(); 
			Stage primaryStage = new Stage();
			FXMLLoader loader = new FXMLLoader();
			Pane root=loader.load(getClass().getResource("/application/front/fxml/Amministratore.fxml").openStream());
			Scene scene = new Scene(root);
			primaryStage.setScene(scene);
			primaryStage.show();		
		}catch(Exception e){
			
		}
	}

}
